from pydantic import BaseModel
from pydub import AudioSegment
from typing import List, Optional

OUTPUTS_FOLDER = 'outputs/'
BARS = 16

TITLE = "Audio Generator API"
DESC = "Generate audio files from MIDI"
VERSION = "0.1"
HOST = "127.0.0.1"
PORT = 5000

DELETE_FILE_INTERVAL = 10  # in seconds

Instruments = {
    '0': {
        '28': AudioSegment.from_file('audio/piano_notes/28.mp3', format='mp3'),
        '29': AudioSegment.from_file('audio/piano_notes/29.mp3', format='mp3'),
        '30': AudioSegment.from_file('audio/piano_notes/30.mp3', format='mp3'),
        '31': AudioSegment.from_file('audio/piano_notes/31.mp3', format='mp3'),
        '32': AudioSegment.from_file('audio/piano_notes/32.mp3', format='mp3'),
        '33': AudioSegment.from_file('audio/piano_notes/33.mp3', format='mp3'),
        '34': AudioSegment.from_file('audio/piano_notes/34.mp3', format='mp3'),
        '35': AudioSegment.from_file('audio/piano_notes/35.mp3', format='mp3'),
        '36': AudioSegment.from_file('audio/piano_notes/36.mp3', format='mp3'),
        '37': AudioSegment.from_file('audio/piano_notes/37.mp3', format='mp3'),
        '38': AudioSegment.from_file('audio/piano_notes/38.mp3', format='mp3'),
        '39': AudioSegment.from_file('audio/piano_notes/39.mp3', format='mp3'),
        '40': AudioSegment.from_file('audio/piano_notes/40.mp3', format='mp3'),
        '41': AudioSegment.from_file('audio/piano_notes/41.mp3', format='mp3'),
        '42': AudioSegment.from_file('audio/piano_notes/42.mp3', format='mp3'),
        '43': AudioSegment.from_file('audio/piano_notes/43.mp3', format='mp3'),
        '44': AudioSegment.from_file('audio/piano_notes/44.mp3', format='mp3'),
        '45': AudioSegment.from_file('audio/piano_notes/45.mp3', format='mp3'),
        '46': AudioSegment.from_file('audio/piano_notes/46.mp3', format='mp3'),
        '47': AudioSegment.from_file('audio/piano_notes/47.mp3', format='mp3'),
        '48': AudioSegment.from_file('audio/piano_notes/48.mp3', format='mp3'),
        '49': AudioSegment.from_file('audio/piano_notes/49.mp3', format='mp3'),
        '50': AudioSegment.from_file('audio/piano_notes/50.mp3', format='mp3'),
        '51': AudioSegment.from_file('audio/piano_notes/51.mp3', format='mp3'),
        '52': AudioSegment.from_file('audio/piano_notes/52.mp3', format='mp3'),
        '53': AudioSegment.from_file('audio/piano_notes/53.mp3', format='mp3'),
        '54': AudioSegment.from_file('audio/piano_notes/54.mp3', format='mp3'),
        '55': AudioSegment.from_file('audio/piano_notes/55.mp3', format='mp3'),
        '56': AudioSegment.from_file('audio/piano_notes/56.mp3', format='mp3'),
        '57': AudioSegment.from_file('audio/piano_notes/57.mp3', format='mp3'),
        '58': AudioSegment.from_file('audio/piano_notes/58.mp3', format='mp3'),
        '59': AudioSegment.from_file('audio/piano_notes/59.mp3', format='mp3'),
        '60': AudioSegment.from_file('audio/piano_notes/60.mp3', format='mp3'),
        '61': AudioSegment.from_file('audio/piano_notes/61.mp3', format='mp3'),
        '62': AudioSegment.from_file('audio/piano_notes/62.mp3', format='mp3'),
        '63': AudioSegment.from_file('audio/piano_notes/63.mp3', format='mp3'),
        '64': AudioSegment.from_file('audio/piano_notes/64.mp3', format='mp3'),
        '65': AudioSegment.from_file('audio/piano_notes/65.mp3', format='mp3'),
        '66': AudioSegment.from_file('audio/piano_notes/66.mp3', format='mp3'),
        '67': AudioSegment.from_file('audio/piano_notes/67.mp3', format='mp3'),
        '68': AudioSegment.from_file('audio/piano_notes/68.mp3', format='mp3'),
        '69': AudioSegment.from_file('audio/piano_notes/69.mp3', format='mp3'),
        '70': AudioSegment.from_file('audio/piano_notes/70.mp3', format='mp3'),
        '71': AudioSegment.from_file('audio/piano_notes/71.mp3', format='mp3'),
        '72': AudioSegment.from_file('audio/piano_notes/72.mp3', format='mp3'),
        '73': AudioSegment.from_file('audio/piano_notes/73.mp3', format='mp3'),
        '74': AudioSegment.from_file('audio/piano_notes/74.mp3', format='mp3'),
        '75': AudioSegment.from_file('audio/piano_notes/75.mp3', format='mp3'),
        '76': AudioSegment.from_file('audio/piano_notes/76.mp3', format='mp3'),
        '77': AudioSegment.from_file('audio/piano_notes/77.mp3', format='mp3'),
        '78': AudioSegment.from_file('audio/piano_notes/78.mp3', format='mp3'),
        '79': AudioSegment.from_file('audio/piano_notes/79.mp3', format='mp3'),
        '80': AudioSegment.from_file('audio/piano_notes/80.mp3', format='mp3'),
        '81': AudioSegment.from_file('audio/piano_notes/81.mp3', format='mp3'),
        '82': AudioSegment.from_file('audio/piano_notes/82.mp3', format='mp3'),
        '83': AudioSegment.from_file('audio/piano_notes/83.mp3', format='mp3'),
        '84': AudioSegment.from_file('audio/piano_notes/84.mp3', format='mp3'),
        '85': AudioSegment.from_file('audio/piano_notes/85.mp3', format='mp3'),
        '86': AudioSegment.from_file('audio/piano_notes/86.mp3', format='mp3'),
        '87': AudioSegment.from_file('audio/piano_notes/87.mp3', format='mp3'),
        '88': AudioSegment.from_file('audio/piano_notes/88.mp3', format='mp3'),
        '89': AudioSegment.from_file('audio/piano_notes/89.mp3', format='mp3'),
        '90': AudioSegment.from_file('audio/piano_notes/90.mp3', format='mp3'),
        '91': AudioSegment.from_file('audio/piano_notes/91.mp3', format='mp3'),
        '92': AudioSegment.from_file('audio/piano_notes/92.mp3', format='mp3'),
        '93': AudioSegment.from_file('audio/piano_notes/93.mp3', format='mp3'),
        '94': AudioSegment.from_file('audio/piano_notes/94.mp3', format='mp3'),
        '95': AudioSegment.from_file('audio/piano_notes/95.mp3', format='mp3'),
        '96': AudioSegment.from_file('audio/piano_notes/96.mp3', format='mp3'),
        '97': AudioSegment.from_file('audio/piano_notes/97.mp3', format='mp3'),
    }
}


class Midi(BaseModel):
    zero: Optional[List[int]] = None
    one: Optional[List[int]] = None
    two: Optional[List[int]] = None
    three: Optional[List[int]] = None
    four: Optional[List[int]] = None
    five: Optional[List[int]] = None
    six: Optional[List[int]] = None
    seven: Optional[List[int]] = None
    eight: Optional[List[int]] = None
    nine: Optional[List[int]] = None
    ten0: Optional[List[int]] = None
    ten1: Optional[List[int]] = None
    ten2: Optional[List[int]] = None
    ten3: Optional[List[int]] = None
    ten4: Optional[List[int]] = None
    ten5: Optional[List[int]] = None
    ten6: Optional[List[int]] = None
    ten7: Optional[List[int]] = None
    ten8: Optional[List[int]] = None
    ten9: Optional[List[int]] = None
    twenty0: Optional[List[int]] = None
    twenty1: Optional[List[int]] = None
    twenty2: Optional[List[int]] = None
    twenty3: Optional[List[int]] = None
    twenty4: Optional[List[int]] = None
    twenty5: Optional[List[int]] = None
    twenty6: Optional[List[int]] = None
    twenty7: Optional[List[int]] = None
    twenty8: Optional[List[int]] = None
    twenty9: Optional[List[int]] = None
    thirty0: Optional[List[int]] = None
    thirty1: Optional[List[int]] = None
    thirty2: Optional[List[int]] = None
    thirty3: Optional[List[int]] = None
    thirty4: Optional[List[int]] = None
    thirty5: Optional[List[int]] = None
    thirty6: Optional[List[int]] = None
    thirty7: Optional[List[int]] = None
    thirty8: Optional[List[int]] = None
    thirty9: Optional[List[int]] = None
    fourty0: Optional[List[int]] = None
    fourty1: Optional[List[int]] = None
    fourty2: Optional[List[int]] = None
    fourty3: Optional[List[int]] = None
    fourty4: Optional[List[int]] = None
    fourty5: Optional[List[int]] = None
    fourty6: Optional[List[int]] = None
    fourty7: Optional[List[int]] = None
    fourty8: Optional[List[int]] = None
    fourty9: Optional[List[int]] = None
    fifty0: Optional[List[int]] = None
    fifty1: Optional[List[int]] = None
    fifty2: Optional[List[int]] = None
    fifty3: Optional[List[int]] = None
    fifty4: Optional[List[int]] = None
    fifty5: Optional[List[int]] = None
    fifty6: Optional[List[int]] = None
    fifty7: Optional[List[int]] = None
    fifty8: Optional[List[int]] = None
    fifty9: Optional[List[int]] = None
    sixty0: Optional[List[int]] = None
    sixty1: Optional[List[int]] = None
    sixty2: Optional[List[int]] = None
    sixty3: Optional[List[int]] = None
    sixty4: Optional[List[int]] = None
    sixty5: Optional[List[int]] = None
    sixty6: Optional[List[int]] = None
    sixty7: Optional[List[int]] = None
    sixty8: Optional[List[int]] = None
    sixty9: Optional[List[int]] = None
    seventy0: Optional[List[int]] = None
    seventy1: Optional[List[int]] = None
    seventy2: Optional[List[int]] = None
    seventy3: Optional[List[int]] = None
    seventy4: Optional[List[int]] = None
    seventy5: Optional[List[int]] = None
    seventy6: Optional[List[int]] = None
    seventy7: Optional[List[int]] = None
    seventy8: Optional[List[int]] = None
    seventy9: Optional[List[int]] = None
    eighty0: Optional[List[int]] = None
    eighty1: Optional[List[int]] = None
    eighty2: Optional[List[int]] = None
    eighty3: Optional[List[int]] = None
    eighty4: Optional[List[int]] = None
    eighty5: Optional[List[int]] = None
    eighty6: Optional[List[int]] = None
    eighty7: Optional[List[int]] = None
    eighty8: Optional[List[int]] = None
    eighty9: Optional[List[int]] = None
    ninety0: Optional[List[int]] = None
    ninety1: Optional[List[int]] = None
    ninety2: Optional[List[int]] = None
    ninety3: Optional[List[int]] = None
    ninety4: Optional[List[int]] = None
    ninety5: Optional[List[int]] = None
    ninety6: Optional[List[int]] = None
    ninety7: Optional[List[int]] = None
    ninety8: Optional[List[int]] = None
    ninety9: Optional[List[int]] = None
    onehundred0: Optional[List[int]] = None
    onehundred1: Optional[List[int]] = None
    onehundred2: Optional[List[int]] = None
    onehundred3: Optional[List[int]] = None
    onehundred4: Optional[List[int]] = None
    onehundred5: Optional[List[int]] = None
    onehundred6: Optional[List[int]] = None
    onehundred7: Optional[List[int]] = None
    onehundred8: Optional[List[int]] = None
    onehundred9: Optional[List[int]] = None
    oneHundred10: Optional[List[int]] = None
    oneHundred11: Optional[List[int]] = None
    oneHundred12: Optional[List[int]] = None
    oneHundred13: Optional[List[int]] = None
    oneHundred14: Optional[List[int]] = None
    oneHundred15: Optional[List[int]] = None
    oneHundred16: Optional[List[int]] = None
    oneHundred17: Optional[List[int]] = None
    oneHundred18: Optional[List[int]] = None
    oneHundred19: Optional[List[int]] = None


class Vels(BaseModel):
    zero: Optional[List[float]] = None
    one: Optional[List[float]] = None
    two: Optional[List[float]] = None
    three: Optional[List[float]] = None
    four: Optional[List[float]] = None
    five: Optional[List[float]] = None
    six: Optional[List[float]] = None
    seven: Optional[List[float]] = None
    eight: Optional[List[float]] = None
    nine: Optional[List[float]] = None
    ten0: Optional[List[float]] = None
    ten1: Optional[List[float]] = None
    ten2: Optional[List[float]] = None
    ten3: Optional[List[float]] = None
    ten4: Optional[List[float]] = None
    ten5: Optional[List[float]] = None
    ten6: Optional[List[float]] = None
    ten7: Optional[List[float]] = None
    ten8: Optional[List[float]] = None
    ten9: Optional[List[float]] = None
    twenty0: Optional[List[float]] = None
    twenty1: Optional[List[float]] = None
    twenty2: Optional[List[float]] = None
    twenty3: Optional[List[float]] = None
    twenty4: Optional[List[float]] = None
    twenty5: Optional[List[float]] = None
    twenty6: Optional[List[float]] = None
    twenty7: Optional[List[float]] = None
    twenty8: Optional[List[float]] = None
    twenty9: Optional[List[float]] = None
    thirty0: Optional[List[float]] = None
    thirty1: Optional[List[float]] = None
    thirty2: Optional[List[float]] = None
    thirty3: Optional[List[float]] = None
    thirty4: Optional[List[float]] = None
    thirty5: Optional[List[float]] = None
    thirty6: Optional[List[float]] = None
    thirty7: Optional[List[float]] = None
    thirty8: Optional[List[float]] = None
    thirty9: Optional[List[float]] = None
    fourty0: Optional[List[float]] = None
    fourty1: Optional[List[float]] = None
    fourty2: Optional[List[float]] = None
    fourty3: Optional[List[float]] = None
    fourty4: Optional[List[float]] = None
    fourty5: Optional[List[float]] = None
    fourty6: Optional[List[float]] = None
    fourty7: Optional[List[float]] = None
    fourty8: Optional[List[float]] = None
    fourty9: Optional[List[float]] = None
    fifty0: Optional[List[float]] = None
    fifty1: Optional[List[float]] = None
    fifty2: Optional[List[float]] = None
    fifty3: Optional[List[float]] = None
    fifty4: Optional[List[float]] = None
    fifty5: Optional[List[float]] = None
    fifty6: Optional[List[float]] = None
    fifty7: Optional[List[float]] = None
    fifty8: Optional[List[float]] = None
    fifty9: Optional[List[float]] = None
    sixty0: Optional[List[float]] = None
    sixty1: Optional[List[float]] = None
    sixty2: Optional[List[float]] = None
    sixty3: Optional[List[float]] = None
    sixty4: Optional[List[float]] = None
    sixty5: Optional[List[float]] = None
    sixty6: Optional[List[float]] = None
    sixty7: Optional[List[float]] = None
    sixty8: Optional[List[float]] = None
    sixty9: Optional[List[float]] = None
    seventy0: Optional[List[float]] = None
    seventy1: Optional[List[float]] = None
    seventy2: Optional[List[float]] = None
    seventy3: Optional[List[float]] = None
    seventy4: Optional[List[float]] = None
    seventy5: Optional[List[float]] = None
    seventy6: Optional[List[float]] = None
    seventy7: Optional[List[float]] = None
    seventy8: Optional[List[float]] = None
    seventy9: Optional[List[float]] = None
    eighty0: Optional[List[float]] = None
    eighty1: Optional[List[float]] = None
    eighty2: Optional[List[float]] = None
    eighty3: Optional[List[float]] = None
    eighty4: Optional[List[float]] = None
    eighty5: Optional[List[float]] = None
    eighty6: Optional[List[float]] = None
    eighty7: Optional[List[float]] = None
    eighty8: Optional[List[float]] = None
    eighty9: Optional[List[float]] = None
    ninety0: Optional[List[float]] = None
    ninety1: Optional[List[float]] = None
    ninety2: Optional[List[float]] = None
    ninety3: Optional[List[float]] = None
    ninety4: Optional[List[float]] = None
    ninety5: Optional[List[float]] = None
    ninety6: Optional[List[float]] = None
    ninety7: Optional[List[float]] = None
    ninety8: Optional[List[float]] = None
    ninety9: Optional[List[float]] = None
    onehundred0: Optional[List[float]] = None
    onehundred1: Optional[List[float]] = None
    onehundred2: Optional[List[float]] = None
    onehundred3: Optional[List[float]] = None
    onehundred4: Optional[List[float]] = None
    onehundred5: Optional[List[float]] = None
    onehundred6: Optional[List[float]] = None
    onehundred7: Optional[List[float]] = None
    onehundred8: Optional[List[float]] = None
    onehundred9: Optional[List[float]] = None
    oneHundred10: Optional[List[float]] = None
    oneHundred11: Optional[List[float]] = None
    oneHundred12: Optional[List[float]] = None
    oneHundred13: Optional[List[float]] = None
    oneHundred14: Optional[List[float]] = None
    oneHundred15: Optional[List[float]] = None
    oneHundred16: Optional[List[float]] = None
    oneHundred17: Optional[List[float]] = None
    oneHundred18: Optional[List[float]] = None
    oneHundred19: Optional[List[float]] = None


class Durs(BaseModel):
    zero: Optional[List[int]] = None
    one: Optional[List[int]] = None
    two: Optional[List[int]] = None
    three: Optional[List[int]] = None
    four: Optional[List[int]] = None
    five: Optional[List[int]] = None
    six: Optional[List[int]] = None
    seven: Optional[List[int]] = None
    eight: Optional[List[int]] = None
    nine: Optional[List[int]] = None
    ten0: Optional[List[int]] = None
    ten1: Optional[List[int]] = None
    ten2: Optional[List[int]] = None
    ten3: Optional[List[int]] = None
    ten4: Optional[List[int]] = None
    ten5: Optional[List[int]] = None
    ten6: Optional[List[int]] = None
    ten7: Optional[List[int]] = None
    ten8: Optional[List[int]] = None
    ten9: Optional[List[int]] = None
    twenty0: Optional[List[int]] = None
    twenty1: Optional[List[int]] = None
    twenty2: Optional[List[int]] = None
    twenty3: Optional[List[int]] = None
    twenty4: Optional[List[int]] = None
    twenty5: Optional[List[int]] = None
    twenty6: Optional[List[int]] = None
    twenty7: Optional[List[int]] = None
    twenty8: Optional[List[int]] = None
    twenty9: Optional[List[int]] = None
    thirty0: Optional[List[int]] = None
    thirty1: Optional[List[int]] = None
    thirty2: Optional[List[int]] = None
    thirty3: Optional[List[int]] = None
    thirty4: Optional[List[int]] = None
    thirty5: Optional[List[int]] = None
    thirty6: Optional[List[int]] = None
    thirty7: Optional[List[int]] = None
    thirty8: Optional[List[int]] = None
    thirty9: Optional[List[int]] = None
    fourty0: Optional[List[int]] = None
    fourty1: Optional[List[int]] = None
    fourty2: Optional[List[int]] = None
    fourty3: Optional[List[int]] = None
    fourty4: Optional[List[int]] = None
    fourty5: Optional[List[int]] = None
    fourty6: Optional[List[int]] = None
    fourty7: Optional[List[int]] = None
    fourty8: Optional[List[int]] = None
    fourty9: Optional[List[int]] = None
    fifty0: Optional[List[int]] = None
    fifty1: Optional[List[int]] = None
    fifty2: Optional[List[int]] = None
    fifty3: Optional[List[int]] = None
    fifty4: Optional[List[int]] = None
    fifty5: Optional[List[int]] = None
    fifty6: Optional[List[int]] = None
    fifty7: Optional[List[int]] = None
    fifty8: Optional[List[int]] = None
    fifty9: Optional[List[int]] = None
    sixty0: Optional[List[int]] = None
    sixty1: Optional[List[int]] = None
    sixty2: Optional[List[int]] = None
    sixty3: Optional[List[int]] = None
    sixty4: Optional[List[int]] = None
    sixty5: Optional[List[int]] = None
    sixty6: Optional[List[int]] = None
    sixty7: Optional[List[int]] = None
    sixty8: Optional[List[int]] = None
    sixty9: Optional[List[int]] = None
    seventy0: Optional[List[int]] = None
    seventy1: Optional[List[int]] = None
    seventy2: Optional[List[int]] = None
    seventy3: Optional[List[int]] = None
    seventy4: Optional[List[int]] = None
    seventy5: Optional[List[int]] = None
    seventy6: Optional[List[int]] = None
    seventy7: Optional[List[int]] = None
    seventy8: Optional[List[int]] = None
    seventy9: Optional[List[int]] = None
    eighty0: Optional[List[int]] = None
    eighty1: Optional[List[int]] = None
    eighty2: Optional[List[int]] = None
    eighty3: Optional[List[int]] = None
    eighty4: Optional[List[int]] = None
    eighty5: Optional[List[int]] = None
    eighty6: Optional[List[int]] = None
    eighty7: Optional[List[int]] = None
    eighty8: Optional[List[int]] = None
    eighty9: Optional[List[int]] = None
    ninety0: Optional[List[int]] = None
    ninety1: Optional[List[int]] = None
    ninety2: Optional[List[int]] = None
    ninety3: Optional[List[int]] = None
    ninety4: Optional[List[int]] = None
    ninety5: Optional[List[int]] = None
    ninety6: Optional[List[int]] = None
    ninety7: Optional[List[int]] = None
    ninety8: Optional[List[int]] = None
    ninety9: Optional[List[int]] = None
    onehundred0: Optional[List[int]] = None
    onehundred1: Optional[List[int]] = None
    onehundred2: Optional[List[int]] = None
    onehundred3: Optional[List[int]] = None
    onehundred4: Optional[List[int]] = None
    onehundred5: Optional[List[int]] = None
    onehundred6: Optional[List[int]] = None
    onehundred7: Optional[List[int]] = None
    onehundred8: Optional[List[int]] = None
    onehundred9: Optional[List[int]] = None
    oneHundred10: Optional[List[int]] = None
    oneHundred11: Optional[List[int]] = None
    oneHundred12: Optional[List[int]] = None
    oneHundred13: Optional[List[int]] = None
    oneHundred14: Optional[List[int]] = None
    oneHundred15: Optional[List[int]] = None
    oneHundred16: Optional[List[int]] = None
    oneHundred17: Optional[List[int]] = None
    oneHundred18: Optional[List[int]] = None
    oneHundred19: Optional[List[int]] = None


class Data(BaseModel):
    bars: int
    instID: str
    tempo: int




